### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by StefanNestorov** [ost-sdk/ostkit-ios#1] opened 2018-05-19 21:45 UTC
Hi, can you successfully use this wrapper ? I get some strange error for creating user and list of users:

```
success : 2 elements
    ▿ 0 : 2 elements
      - key : success
      - value : 0
    ▿ 1 : 2 elements
      - key : err
      ▿ value : 4 elements
        ▿ 0 : 2 elements
          - key : code
          - value : BAD_REQUEST
        ▿ 1 : 2 elements
          - key : error_data
          ▿ value : 1 element
            ▿ 0 : 2 elements
              ▿ 0 : 2 elements
                - key : msg
                - value : invalid id passed
              ▿ 1 : 2 elements
                - key : parameter
                - value : id
        ▿ 2 : 2 elements
          - key : internal_id
          - value : s_cu_fu_2
        ▿ 3 : 2 elements
          - key : msg
          - value : At least one parameter is invalid or missing. See "err.error_data" array for more details.
```

**Comment by duong1521991** [comment] 2018-05-20 05:07
@StefanNestorov  hi, can you provide `curl`?. It's printed in console when you use sdk in debugMode. So i can reproduce bug easier.

**Comment by duong1521991** [comment] 2018-05-24 03:54
@StefanNestorov  i will close this issue because no interaction for few day. You can reopen if needed

**Closed by duong1521991** 2018-05-24 03:54 UTC
Labels: bug
